apiVersion: v1
kind: Secret
metadata:
  name: repo-pull-secret
data:
  .dockerconfigjson: ""
type: kubernetes.io/dockerconfigjson
## The data value must be a string code in base64
# {"auths":{"$REGISTRY_URL":{"username":"$USERNAME","password":"$PASSWORD","email":"$EMAIL","auth":"$AUTH"}}}
#
# REGISTRY_URL: registry.gitlab.com
# USERNAME: Repository username
# PASSWORD: Repository password (Try to use your token account)
# EMAIL: Repository email
# AUTH: string code in base 64 with format "repository_username:repository_password" (token account)
